language: rust
sudo: false
cache:
  directories:
    - $HOME/.cargo
rust:
  - stable
  - beta
  - nightly
env:
  - RUSTFLAGS="-D warnings"
os:
  - linux
  - osx
dist: bionic
branches:
  only:
    - dev
script:
  - cd palette_derive
  - cargo build -v

  - cd ../palette
  - cargo build -v
  - cargo test -v
  - bash ../scripts/test_features.sh

  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cd ../no_std_test;
      cargo build -v --features nightly;
    fi

  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then
      rustup target add thumbv6m-none-eabi;
      cargo build -v --features nightly --target thumbv6m-none-eabi;
    fi;

  - cd ..
  - cargo doc --all --exclude no_std_test
after_success:
  - sh scripts/upload_doc.sh
