language: rust
sudo: false
cache:
  directories:
    - $HOME/.cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
dist:
  - bionic
branches:
  only:
    - master
    - staging
    - trying
    - /^\d+\.\d+$/
script:
  - cd palette_derive
  - cargo build -v --features strict

  - cd ../palette
  - cargo build -v --features strict
  - cargo test -v --features strict
  - bash ../scripts/test_features.sh

  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cd ../no_std_test;
      cargo build -v -Z config-profile;
    fi

  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then
      rustup target add thumbv6m-none-eabi;
      cargo build -v --target thumbv6m-none-eabi -Z config-profile;
    fi;

  - cd ..
  - cargo doc --all --exclude no_std_test
after_success:
  - sh scripts/upload_doc.sh
